apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: microservice-app
  name: zipkin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: microservice-app
        service: zipkin
    spec:
      containers:
      - env:
        image: openzipkin/zipkin
        name: zipkin
        ports:
        - containerPort: 9411
        - containerPort: 9410
      restartPolicy: Always
