name: smarthears_mobile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  local_auth: ^2.0.2
  flutter_login: ^3.2.0
  geolocator: ^8.2.1
  flutter_secure_storage: ^5.0.2
  carousel_slider: ^4.1.1
  google_fonts: ^3.0.1
  crypto: ^3.0.2
  get: ^4.6.5
  url_launcher: ^6.1.2
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  device_info: ^2.0.3
  pull_to_refresh: ^2.0.0
  location_platform_interface: ^2.3.0
  flutter_svg: ^1.1.0
  flutter_html: ^3.0.0-alpha.3
  firebase_dynamic_links: ^4.2.5
  flutter_cache_manager: ^3.3.0
  permission_handler_platform_interface: ^3.7.0
  sign_in_with_apple: ^4.0.0
  flutter_tagging:
    git:
      url: https://github.com/moninm/flutter_tagging
  modal_bottom_sheet: ^2.0.1
  get_it: ^7.2.0
  firebase_messaging: ^11.4.1
  google_sign_in: ^5.3.1
  firebase_auth: ^3.3.19
  global_configuration: ^2.0.0-nullsafety.1
  firebase_core: ^1.17.1
  permission_handler: ^8.1.6
  devicelocale: ^0.5.1
  equatable: ^2.0.3
  jwt_decoder: ^2.0.1
  like_button: ^2.0.4
  flutter_app_badger: ^1.4.0
  badges: ^2.0.2
  curved_navigation_bar: ^1.0.3





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets:
    - assets/cfg/
  uses-material-design: true