name: smarthears_mobile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  local_auth: ^2.0.2
  flutter_login: ^3.2.0
  flutter_secure_storage: ^5.0.2
  carousel_slider: ^4.1.1
  google_fonts: ^3.0.1
  url_launcher: ^6.1.2
  shared_preferences: ^2.0.15
  device_info: ^2.0.3
  firebase_dynamic_links: ^4.2.5
  get_it: ^7.2.0
  google_sign_in: ^5.3.2
  firebase_auth: ^3.3.19
  global_configuration: ^2.0.0-nullsafety.1
  firebase_core: ^1.17.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true