name: CMake Build

on: [push, pull_request]

env:
  CMAKE_VERSION: 3.23.0
  NINJA_VERSION: 1.10.2
  BUILD_TYPE: Release
  CCACHE_VERSION: 4.6

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: POC2/app/src/main
    steps:
      - uses: actions/checkout@v2
      - name: install CMake
        run: sudo apt-get install cmake
      
      - name: check Version
        run: cmake --version
      
      - name: build CMake
        working-directory: ./POC2/app/src/main
        run: cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug && make && ls
      
      # - name: launch unit tests
      #   working-directory: ./POC2/app/src/main/Doctest_tests
      #   run: cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug && make && ./Doctest_tests_run
