name: Unit-Tests Android app

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!release*'
      - '!main'

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        version: 11
    - name: Start Unit Test
      run: chmod +x gradlew && ./gradlew testDebugUnitTest
